- name: Load join command
  vars:
    join_file_path: "{{ join_command_dir }}/join_command_{{ cluster_group }}.txt"
  command: "cat {{ join_file_path }}"
  register: join_command_raw
  changed_when: false
  delegate_to: localhost

- name: Extract join command
  set_fact:
    join_command: "{{ join_command_raw.stdout.split('=')[1] }}"

- name: Check if node is already joined
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: Join Kubernetes cluster
  command: "{{ join_command }}"
  args:
    creates: /etc/kubernetes/kubelet.conf  # Proper idempotency check
  register: join_result
  retries: 4
  delay: 10
  until: join_result is succeeded
  ignore_errors: yes  # Temporary for debugging