- name: Find control plane host for this worker
  set_fact:
    controlplane_host: >-
      {{ groups
          | dict2items
          | selectattr('value', 'contains', inventory_hostname)
          | selectattr('key', 'match', '^cluster[0-9]+$')
          | map(attribute='value')
          | map('select', 'search', 'controlplane')
          | map('first')
          | list
          | first }}
  tags: always

- name: Extract cluster group name
  set_fact:
    cluster_group: "{{ controlplane_host | regex_replace('controlplane$', '') }}"
  tags: always

