- name: Include validation tasks
  include_tasks: validate.yml
  tags: validate

- name: Include cluster joining tasks
  include_tasks: join.yml
  tags: join

- name: Include post-join verification
  include_tasks: post_join.yml
  tags: verify