- name: Set bgp_peers and source ASN
  set_fact:
    source_asn: "{{ kubernetes_clusters[source_cluster].asn }}"
    bgp_peers: "{{ kubernetes_clusters[source_cluster].bgp_peers | default([]) }}"
    kubeconfig_path: "/etc/kubernetes/admin.conf"

- name: Build peer_objects list
  set_fact:
    peer_objects: >-
      {%- set peers = [] -%}
      {%- for peer in bgp_peers -%}
        {%- set target = peer.target_cluster -%}
        {%- set peer_asn = kubernetes_clusters[target].asn -%}
        {%- set _ = peers.append({
          'source_cluster': source_cluster,
          'peer_ip': kubernetes_clusters[target].control_plane,
          'peer_asn': peer_asn,
          'node_name': target ~ "controlplane"
        }) -%}
        {%- for ip in kubernetes_clusters[target].workers -%}
          {%- set index = loop.index -%}
          {%- set _ = peers.append({
            'source_cluster': source_cluster,
            'peer_ip': ip,
            'peer_asn': peer_asn,
            'node_name': target ~ "worker" ~ index
          }) -%}
        {%- endfor -%}
      {%- endfor -%}
      {{ peers }}

- name: Debug peer_objects (optional)
  debug:
    var: peer_objects


- name: Initialize empty BGP peers file
  copy:
    content: "# BGP Peer Configurations for {{ source_cluster }}\n---\n"
    dest: "/tmp/bgp-peers-{{ source_cluster }}.yaml"
    mode: '0644'
  when: peer_objects | length > 0

- name: Append each BGP peer configuration to single file
  block:
    - name: Render individual BGP peer manifest
      template:
        src: "bgp-peer.yaml.j2"
        dest: "/tmp/bgp-peer-temp.yaml"
        mode: '0644'
      vars:
        node_name: "{{ item.node_name }}"
        peer_ip: "{{ item.peer_ip }}"
        peer_asn: "{{ item.peer_asn }}"
        source_cluster: "{{ item.source_cluster }}"
      register: rendered_template
      loop: "{{ peer_objects }}"
      loop_control:
        label: "{{ item.node_name }}"

    - name: Append rendered template to consolidated file
      blockinfile:
        path: "/tmp/bgp-peers-{{ source_cluster }}.yaml"
        block: "{{ lookup('file', '/tmp/bgp-peer-temp.yaml') }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ item.node_name }} #"
      loop: "{{ peer_objects }}"
      loop_control:
        label: "{{ item.node_name }}"

    - name: Clean up temporary file
      file:
        path: "/tmp/bgp-peer-temp.yaml"
        state: absent
  when: peer_objects | length > 0

- name: Apply consolidated BGP peer resources
  command: >
    kubectl apply -f /tmp/bgp-peers-{{ source_cluster }}.yaml
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  when: peer_objects | length > 0