- name: Set source cluster name from inventory_hostname
  set_fact:
    source_cluster: "{{ inventory_hostname | regex_replace('controlplane', '') }}"

- name: Set bgp_peers and source ASN
  set_fact:
    source_asn: "{{ kubernetes_clusters[source_cluster].asn }}"
    bgp_peers: "{{ kubernetes_clusters[source_cluster].bgp_peers | default([]) }}"
    kubeconfig_path: "/etc/kubernetes/admin.conf"

- name: Build peer_objects list
  set_fact:
    peer_objects: >-
      {%- set peers = [] -%}
      {%- for peer in bgp_peers -%}
        {%- set target = peer.target_cluster -%}
        {%- set peer_asn = kubernetes_clusters[target].asn -%}
        {%- set _ = peers.append({
          'source_cluster': source_cluster,
          'peer_ip': kubernetes_clusters[target].control_plane,
          'peer_asn': peer_asn,
          'node_name': target ~ "controlplane"
        }) -%}
        {%- for ip in kubernetes_clusters[target].workers -%}
          {%- set index = loop.index -%}
          {%- set _ = peers.append({
            'source_cluster': source_cluster,
            'peer_ip': ip,
            'peer_asn': peer_asn,
            'node_name': target ~ "worker" ~ index
          }) -%}
        {%- endfor -%}
      {%- endfor -%}
      {{ peers }}

- name: Debug peer_objects (optional)
  debug:
    var: peer_objects

- name: Ensure BGP peer parts directory exists
  file:
    path: "/tmp/bgp-peer-parts"
    state: directory
    mode: '0755'

- name: Render individual BGP peer manifests
  template:
    src: "bgp-peer.yaml.j2"
    dest: "/tmp/bgp-peer-parts/peer-{{ item.node_name }}.yaml"
    mode: '0644'
  loop: "{{ peer_objects }}"
  vars:
    node_name: "{{ item.node_name }}"
    peer_ip: "{{ item.peer_ip }}"
    peer_asn: "{{ item.peer_asn }}"
    source_cluster: "{{ item.source_cluster }}"
  loop_control:
    label: "{{ item.node_name }}"

- name: Assemble consolidated BGP peers file
  assemble:
    src: "/tmp/bgp-peer-parts"
    dest: "/tmp/bgp-peers-{{ source_cluster }}.yaml"
    delimiter: "---\n"

- name: Clean up temporary files
  file:
    path: "/tmp/bgp-peer-parts"
    state: absent

- name: Apply consolidated BGP peer resources
  command: >
    kubectl apply -f /tmp/bgp-peers-{{ source_cluster }}.yaml
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"