- name: Join worker nodes to Kubernetes clusters
  hosts: workers
  become: yes
  gather_facts: no
  environment:
    ANSIBLE_HOST_KEY_CHECKING: "False"
  
  roles:
    - role: kubeadm-join
      tags: join