- name: Install calicoctl and apply CalicoNodeStatus
  hosts: controlplanes
  become: yes
  gather_facts: no
  vars_files:
    - ../vars.yml

  tasks:
    - name: Install calicoctl
      get_url:
        url: https://github.com/projectcalico/calico/releases/download/v3.29.0/calicoctl-linux-amd64
        dest: /usr/local/bin/calicoctl
        mode: '0755'

    - name: Set cluster name from inventory_hostname
      set_fact:
        cluster_name: "{{ inventory_hostname | regex_replace('controlplane', '') }}"
        kubeconfig_path: "/etc/kubernetes/admin.conf"

    - name: Apply CalicoNodeStatus for controlplane node
      template:
        src: ../templates/calico-node-status.yaml.j2
        dest: "/tmp/{{ cluster_name }}-{{ inventory_hostname }}-node-status.yaml"
        mode: '0644'
      vars:
        node_name: "{{ inventory_hostname }}"

    - name: Apply manifest
      command: >
        kubectl apply -f /tmp/{{ cluster_name }}-{{ inventory_hostname }}-node-status.yaml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
