- name: Join all workers using the correct join command
  hosts: workers
  become: yes
  gather_facts: no
  tasks:
    - name: Find the cluster this worker belongs to
      set_fact:
        cluster_group: >-
          {{ groups['clusters'] | select('in', group_names) | list | first }}

    - name: Identify control plane of the cluster
      set_fact:
        controlplane_host: "{{ groups[cluster_group] | select('search', 'controlplane') | list | first }}"

    - name: Get the join command from the control plane
      set_fact:
        join_command: "{{ hostvars[controlplane_host].join_command }}"

    - name: Check if the node is already joined
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf

    - name: Debug the join command
      debug:
        msg: "Worker {{ inventory_hostname }} will run: {{ join_command }}"
      when: not kubelet_conf.stat.exists

    - name: Join the cluster
      command: "{{ join_command }}"
      when: not kubelet_conf.stat.exists
