- name: Join all workers using the correct join command
  hosts: workers
  become: yes
  gather_facts: no

  tasks:
    - name: Find control plane host from group
      set_fact:
        controlplane_host: >-
          {{ groups
              | dict2items
              | selectattr('value', 'contains', inventory_hostname)
              | selectattr('key', 'match', '^cluster[0-9]+$')
              | map(attribute='value')
              | map('select', 'search', 'controlplane')
              | map('first')
              | list
              | first }}

    - name: Extract cluster group name from control plane hostname
      set_fact:
        cluster_group: "{{ controlplane_host | regex_replace('controlplane$', '') }}"

    - name: Load join command file
      slurp:
        src: "/tmp/join_command_{{ cluster_group }}.txt"
      register: join_file
      delegate_to: localhost

    - name: Set join command from file
      set_fact:
        join_command: "{{ (join_file.content | b64decode).split('=')[1] }}"

    - name: Check if node is already joined
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf

    - name: Join the cluster
      command: "{{ join_command }}"
      when: not kubelet_conf.stat.exists