# main_playbook2.yml
---
- name: Initialize flags
  hosts: localhost
  tasks:
    - name: Set initial state
      set_fact:
        calico_test_failed: false
        kubeadm_failed: false
        worker_join_failed: false

- import_playbook: kubeadm.yml

- name: Check kubeadm status
  hosts: controlplanes
  tasks:
    - name: Verify cluster status
      command: kubectl get nodes
      register: cluster_status
      ignore_errors: yes
      changed_when: false

    - name: Set failure flag if needed
      set_fact:
        kubeadm_failed: true
      when: cluster_status.failed
      delegate_to: "{{ item }}"
      loop: "{{ ansible_play_hosts }}"

- import_playbook: join_workers.yml

